TIPO_RECEITA = "receita"
TIPO_DESPESA = "despesa"

MEIO_CONTA = "conta"
MEIO_CARTAO = "cartao"

TIPOS_LANCAMENTO = [TIPO_RECEITA, TIPO_DESPESA]
MEIOS_FINANCEIROS = [MEIO_CONTA, MEIO_CARTAO]

TIPO_PESSOA = "Pessoa"
TIPO_CENTRO_CUSTO = "Centro de Custo"

AZUL_PRINCIPAL = "#2563EB"
VERDE_PRINCIPAL = "#16A34A"
FUNDO_CLARO = "#F3F4F6"
